import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Home, Articles, About } from "../components/sections";

import styled from "styled-components";
const Wrapper = styled.div`
  max-width: 1440px;
`;
export default function Index() {
  return (
    <Wrapper>
      <Head>
        <title>Easybank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Home />
      <About />
      <Articles />
      <Footer />
    </Wrapper>
  );
}
