import Head from "next/head";
import Heading from "../components/Heading";
import About from "./about";
import Career from "./career";
import Article from "./article";
import Contact from "./contact";
import styled from "styled-components";
const Wrapper = styled.div`
  width: 100%;
`;
export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>Easybank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading />
      <About />
      <Career />
      <Article />
      <Contact />
    </Wrapper>
  );
}
